### PR TITLE
Update to latest versions of Scala

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by jedesah** [comment]
Ping @wemrysi.

**Comment by wemrysi** [comment]
:+1:

**Comment by jedesah** [comment]
@wemrysi Can you do a quick re-review (sanity check) now that I added a changelog and new version to the PR? I tried using the `merge` script but I think it is getting confused by the `SNAPSHOT` in the version file. Should probably work fine after doing it "manually" once as part of this PR.

**Comment by wemrysi** [comment]
I think the filename for the changelog should be `0.0.5.md`, right?

**Comment by sellout** [comment]
It should be “CHANGELOG/revision.md”, right? The merge script should be used here, same as on Matryoshka and Quasar.

**Comment by jedesah** [comment]
@sellout Did you read my previous comment...

**Comment by sellout** [comment]
Ah, I did not. Just reacted to @wemrysi’s 😄

**Comment by wemrysi** [comment]
:+1:

**Pull request merged**
