### PR TITLE
Upgrade to scalaz 7.2.1

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by wemrysi** [comment]
:+1:

**Comment by wemrysi** [comment]
@jedesah Should also bump the minor version.

**Comment by jedesah** [comment]
@wemrysi Good point! minor version? I was thinking more like major version since `scalaz` is being bumped by a major version (semantically).

**Comment by wemrysi** [comment]
@jedesah I just meant literally the minor version since we're still in the 0.x.x stage, I agree that it is a breaking change.

**Comment by sellout** [comment]
@wemrysi What do you think about modifying the `merge` script to be a bit “smarter” about major/minor? (as described in https://github.com/slamdata/matryoshka/pull/20#issuecomment-206571759)

**Comment by wemrysi** [comment]
@sellout Aye, I think that's a good idea. I also think the file names should be semantic/intent based instead of implementation based, which would also make this clearer to humans. Maybe something like `breaking.md`, `addition.md`, `revision.md` (feel free to suggest better ones). This separates intent from implementation.

**Comment by jedesah** [comment]
@wemrysi This should be ready to go.

**Comment by wemrysi** [comment]
LGTM!

**Pull request closed without merging**
