### PR TITLE
Add an instance of Arbitrary for FileName

### PR DESCRIPTION
**Pull request by jedesah**

### CODE REVIEW

**Comment by wemrysi** [comment]
@jedesah If we're going to provide `Arbitrary[FileName]` we should also provide `Arbitrary[DirName]`. I think these concrete instances should be based on some type-indexed versions, similar to `PathOf`, so we can control the generation. Then `PathOf` should be refactored to use these instances instead of creating file and dir names directly.

What do you think?

**Comment by jedesah** [comment]
@wemrysi I think that makes sense.

**Comment by jedesah** [comment]
@wemrysi I still think that your suggestion is the best solution and I need to find the time to do it. I just wanted to get rid of a local change I had on scala-pathy so I could pull down master and do some tests.

**Comment by wemrysi** [comment]
:+1:

**Comment by jedesah** [comment]
@wemrysi Ok, finally got around to updating this.

**Comment by wemrysi** [comment]
Looks good, only comment would be to see if we can make `AlphaCharacters`, `FileNameOf` and `DirNameOf` value classes. :+1:

**Comment by jedesah** [comment]
@wemrysi Was only able to make `AlphaCharacters` a value class.

**Comment by wemrysi** [comment]
Right on, LGTM.

**Pull request merged**
